// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateStatus(ctx context.Context, name string) (Status, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteStatus(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetStatus(ctx context.Context, id int64) (Status, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskForUpdate(ctx context.Context, id int64) (Task, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Category, error)
	ListStatuses(ctx context.Context, arg ListStatusesParams) ([]Status, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
